CREATE DATABASE php-vue CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE php-vue;
CREATE TABLE tb_users (
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(255) NOT NULL,
    lname VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;